### ISSUE TITLE
Fix printing

### ISSUE THREAD

**Issue by KatharineME** [KwatMDPhD/Clean.jl#55]
When run, always prints out: "🗑️ Emptying /var/folders/z_/r2n_rt396917fl9qm_t5h7jm0000gn/T/BioLab"

<img width="761" alt="Screenshot 2023-04-21 at 16 51 58" src="https://user-images.githubusercontent.com/20215501/233745856-89d2b068-3ea8-4437-9a43-a75d0090a8e4.png">

<img width="778" alt="Screenshot 2023-04-21 at 16 51 38" src="https://user-images.githubusercontent.com/20215501/233745867-597293e3-e41c-4b8d-9188-638dd1f4ef0b.png">

**Comment by KwatMDPhD** [comment]
Some emojis use 2 characters. I need to make a helper function to print "<emoji> string..."s. Coming soon...
